### ISSUE TITLE
Task1-Sedreh Nassirnia

### ISSUE THREAD

**Issue by Sedreh** [Sedreh/python-course#1]
[def unique.pdf](https://github.com/Sedreh/python-course/files/2454089/def.unique.pdf)

**Comment by YakutovDmitriy** [comment]
Good!

It is not necessary to create PDF file, I can read code from repository :)

**Comment by Sedreh** [comment]
Hello dear Dmitriy,
thank you for comment. I will send the next 2 homeworks as soon as possible.
